<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="cTrader.Automate" Version="*" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\..\Shared\EmaChartDrawer.cs" Link="EmaChartDrawer.cs" />
  </ItemGroup>
</Project>
